### ISSUE TITLE
218+ SEGFAULT with no restart of daemon

### ISSUE THREAD

**Issue by dustin-hawkins** [nirev/synology-tailscale#22]
**Description**

I've noticed that TailScale will suddenly stop on my DS218+. Looking at the logs, it seems to segfault, and does not autorestart. 

Attached are logs, would it be possible to have the process auto-restart on non-zero exit code? 

**Steps to reproduce**
```
2020/08/23 07:07:14 magicsock: closing connection to derp-1 (idle), age 4m18s
2020/08/23 07:07:14 magicsock: 1 active derp conns: derp-2=cr4s,wr4s
2020/08/23 07:07:34 magicsock: starting endpoint update (periodic)
2020/08/23 07:07:36 netcheck: netcheck: no IPv4 UDP STUN replies
2020/08/23 07:07:36 netcheck: udp=false v6=false mapvarydest= hair= derp=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x884b78]

goroutine 25596 [running]:
tailscale.com/wgengine/magicsock.(*Conn).setNearestDERP(0xc0001009a0, 0x9, 0xc000591d00)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:474 +0x188
tailscale.com/wgengine/magicsock.(*Conn).updateNetInfo(0xc0001009a0, 0xaaa640, 0xc002a44180, 0x0, 0x0, 0x0)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:356 +0x379
tailscale.com/wgengine/magicsock.(*Conn).determineEndpoints(0xc0001009a0, 0xaaa5c0, 0xc00001eac0, 0x1, 0x1, 0xc001604358, 0x8a3300, 0x8a89e6, 0xc0001006e0)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:498 +0x5d
tailscale.com/wgengine/magicsock.(*Conn).updateEndpoints(0xc0001009a0, 0x9dfe30, 0x8)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:297 +0x125
created by tailscale.com/wgengine/magicsock.(*Conn).ReSTUN
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:1446 +0x1ee

```

**Expected behavior**

A restart of the service on an unexpected exit.	

**Synology NAS model**
E.g. DS218+

**Comment by nirev** [comment]
@dustin-hawkins thank you for the detailed report!
I'm aiming to have  a look at this weekend. Hopefully not too complicated.

**Comment by nirev** [comment]
Adding more context here on how to do it:

- DSM 6.2 is using upstart
- There's a default upstart job created for each package under `/etc/init/pkgctl-${PKG_NAME}.conf` that looks like this
```
# Generated by Package Center. DO NOT EDIT.
start on syno.pkgctl.pkgstart
stop on syno.pkgctl.shutdown

cgroup cpuacct "pkgctl-tailscale"
cgroup memory "pkgctl-tailscale"

console log
env SELF="tailscale"

pre-start script
	/usr/syno/sbin/synopkgctl start "$SELF"
	/sbin/initctl emit --no-wait syno.pkgctl.started NAME="$SELF"
end script

post-stop script
	/sbin/initctl emit syno.pkgctl.stopping NAME="$SELF"
	/usr/syno/sbin/synopkgctl stop "$SELF"
end script
```

- synopkgctl will call the `start-stop-status` script of the package

## how to add automatic respawn

A way to have automatic respawn would be to have *another* upstart job.
This can be done by adding the job config to the package under `conf/upstart/pkg-${PKG_NAME}-<something>.conf`
Once the package is installed, this file will be copied to `/etc/init` alongside the default generated one.

Then, we can modify `start-stop-status` to use upstart:

eg:
TAILSCALED=pkg-tailscale-tailscaled
start => `start ${TAILSCALED}` 
stop => `stop ${TAILSCALED}`
status => `initctl status ${TAILSCALED}`
```

**Comment by dustin-hawkins** [comment]
Its a shame the `respawn` directive cant be added into the auto-created upstart job. That would take care of it, I think.

**Comment by nirev** [comment]
@dustin-hawkins definitely agree. this isn't even mentioned in the synology package development guide.
I assumed that it would have respawn by default and, as you can note, didn't even check (my bad)

I had a look at `docker` and `apache` packages, and both do it like this with a separate upstart job.

**Comment by jucor** [comment]
Observing exactly the same behaviour here on my DSM 218+ in my logs too, same error. Respawn would be useful :)

```
2020/09/06 13:50:31 Accept: TCP{100.74.46.46:5001 > 100.67.104.37:33112} 52 ok out
2020/09/06 13:50:36 25.9M/58.8M [RJsQX] - Received handshake init from 192.168.1.16:53164
2020/09/06 13:50:36 26.0M/58.8M [RJsQX] - Send handshake response [127.3.3.40:8, 81.2.76.170:53164, 192.168.1.16:53164*]
2020/09/06 13:50:36 magicsock: adding connection to derp-8 for [RJsQX]
2020/09/06 13:50:36 magicsock: rx [RJsQX] from 192.168.1.16:53164 (2/3), set as new priority
2020/09/06 13:50:36 26.0M/58.8M [RJsQX] - Received keepalive from 192.168.1.16:53164
2020/09/06 13:50:37 26.0M/58.8M [RJsQX] - ConsumeMessageInitiation: handshake replay @ [64 0 0 0 95 84 219 38 29 0 0 0]
2020/09/06 13:50:37 26.0M/58.8M Received invalid initiation message from 127.3.3.40:4
2020/09/06 13:50:42 Accept: TCP{100.67.104.37:33112 > 100.74.46.46:5001} 272 tcp non-syn
2020/09/06 13:50:42 magicsock: starting endpoint update (periodic)
2020/09/06 13:50:44 netcheck: netcheck: no IPv4 UDP STUN replies
2020/09/06 13:50:44 netcheck: udp=false v6=false mapvarydest= hair= derp=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x884b78]

goroutine 14977 [running]:
tailscale.com/wgengine/magicsock.(*Conn).setNearestDERP(0xc000020160, 0x8, 0xc002b71d00)
    /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:474 +0x188
tailscale.com/wgengine/magicsock.(*Conn).updateNetInfo(0xc000020160, 0xaaa640, 0xc00005d4a0, 0x0, 0x0, 0x0)
    /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:356 +0x379
tailscale.com/wgengine/magicsock.(*Conn).determineEndpoints(0xc000020160, 0xaaa5c0, 0xc00001e080, 0x1, 0x1, 0x85d0e3, 0xc0017c5898, 0x2540be400, 0xc0002fc100)
    /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:498 +0x5d
tailscale.com/wgengine/magicsock.(*Conn).updateEndpoints(0xc000020160, 0x9dfe30, 0x8)
    /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:297 +0x125
created by tailscale.com/wgengine/magicsock.(*Conn).ReSTUN
    /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:1446 +0x1ee
```

**Comment by jucor** [comment]
@nirev  Thanks for the update to 1.1.135, might help making Tailscale more stable on DS218+ :) Did you have any luck with the autorespawn, by chance, please?
